substitutions:
  name: jk-bms-master
  device_description: "Connect any bms to an inverter"
  external_components_source: github://rfdarter/esphome-jk-bms@friendly
  external_components_source_2: github://rfDarter/esphome-bms-to-inverter@main
  mac_address: C8:47:80:05:73:8C
  # Defaults to "JK02" (hardware version >= 6.0 and < 11.0)
  # Please use "JK02_32S" if you own a new JK-BMS >= hardware version 11.0 (f.e. JK-B2A8S20P hw 11.XW, sw 11.26)
  # Please use "JK04" if you have some old JK-BMS <= hardware version 3.0 (f.e. JK-B2A16S hw 3.0, sw. 3.3.0)
  protocol_version: JK02_32S

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "rfdarter.esphome-bms-to-inverter"
    version: 1.0.0

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s
  - source:
      type: local
      path: 'C:\Users\Matt\Documents\Git\rfdarter-github\esphome-bms-to-inverter\components'
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "esphome-jk-bms-fallback"

ota:
  on_begin:
    then:
      - switch.turn_off: ble_client_switch0
      - logger.log: "BLE connection suspended for OTA update"

logger:
  level: DEBUG
  logs:
    canbus: INFO
    esp32_ble_client: INFO
    esp32_ble_tracker: INFO
    jk_bms_ble: INFO
    bms_to_inverter: DEBUG
    scheduler: INFO
    component: INFO
    sensor: INFO
    mqtt: INFO
    mqtt.idf: INFO
    mqtt.component: INFO
    mqtt.sensor: INFO
    mqtt.switch: INFO
    api.service: INFO
    api: INFO

api:

mqtt:
  broker: !secret mqtt_host
  # username: !secret mqtt_username
  # password: !secret mqtt_password
  id: JK_Battery

web_server:
  js_url: https://deploy-preview-66--esphome-webserver.netlify.app/v3/www.js
  # js_include: "www.js"
  # js_url: ""

captive_portal:

ble_client:
  - mac_address: ${mac_address}
    id: client0

jk_bms_ble:
  - ble_client_id: client0
    protocol_version: ${protocol_version}
    throttle: 5s
    id: bms0

canbus:
  - platform: esp32_can
    id: canbus0
    tx_pin: GPIO5
    rx_pin: GPIO4
    can_id: 4
    bit_rate: 500kbps
    on_frame:
      - can_id: 0x305
        then:
          - lambda: |-
              id(inverter_bms0).on_inverter_message(x);
      - can_id: 0x172
        then:
          - lambda: |-
              id(inverter_bms0).on_slave_message(x);

bms_to_inverter:
  - platform: jk_ble
    id: inverter_bms0
    bms_id: bms0
    device_role: master
    inverter_type: victron
    inverter_connection:
      # type: mqtt
      # mqtt_topic: "enphase/battery"
      type: can
      canbus_id: canbus0
button:
  - platform: template
    name: Set Internal True
    entity_category: config
    on_press:
      lambda: |-
        id(test_text).set_internal(true);

  - platform: template
    name: Set Internal False
    entity_category: config
    on_press:
      lambda: |-
        id(test_text).set_internal(false);

select:
  - platform: bms_to_inverter
    debug_charge_status:
      name: "Debug Charge Status"
    user_charge_logic:
      name: "1. Charge Logic"
    user_can_protocol:
      name: "2. Can Protocol"

text:
  - platform: template
    id: test_text
    name: Test Text
    mode: text
    optimistic: True
    initial_value: "looool"
    entity_category: config

  - platform: bms_to_inverter
    user_battery_name:
      name: "${name} Inverter Battery Name"

binary_sensor:
  - platform: jk_bms_ble
    balancing:
      name: "${name} balancing"
    charging:
      name: "${name} charging"
    discharging:
      name: "${name} discharging"
    heating:
      name: "${name} heating"
    online_status:
      name: "${name} online status"

number:
  - platform: bms_to_inverter
    user_charge_voltage:
      name: "3. Requested Charge Voltage"
      mode: slider
    user_float_voltage:
      name: "4. Requested Float Voltage"
      mode: slider
    user_rebulk_voltage:
      name: "5. Rebulk Voltage"
      mode: slider
    user_max_charge_current:
      name: "6. Max Charge Current"
      mode: slider
      max_value: 600.0 # min and max values can be changed
    user_max_discharge_current:
      name: "7. Max Discharge Current"
    user_absorbtion_time:
      name: "8. Absorbtion Time"
    user_float_time:
      name: "9. Float Time"

  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    cell_count:
      name: "${name} cell count"
      internal: true

sensor:
  - platform: jk_bms_ble
    min_cell_voltage:
      name: "${name} min cell voltage"
    max_cell_voltage:
      name: "${name} max cell voltage"
    min_voltage_cell:
      name: "${name} min voltage cell"
    max_voltage_cell:
      name: "${name} max voltage cell"
    delta_cell_voltage:
      name: "${name} delta cell voltage"
    average_cell_voltage:
      name: "${name} average cell voltage"
    cell_voltage_1:
      name: "${name} cell voltage 1"
    cell_voltage_2:
      name: "${name} cell voltage 2"
    cell_voltage_3:
      name: "${name} cell voltage 3"
    cell_voltage_4:
      name: "${name} cell voltage 4"
    total_voltage:
      name: "${name} total voltage"
    current:
      name: "${name} current"
    power:
      name: "${name} power"
    charging_power:
      name: "${name} charging power"
    discharging_power:
      name: "${name} discharging power"
    temperature_sensor_1:
      name: "${name} temperature sensor 1"
    temperature_sensor_2:
      name: "${name} temperature sensor 2"
    power_tube_temperature:
      name: "${name} power tube temperature"
    state_of_charge:
      name: "${name} state of charge"
    capacity_remaining:
      name: "${name} capacity remaining"
    total_battery_capacity_setting:
      name: "${name} total battery capacity setting"
    charging_cycles:
      name: "${name} charging cycles"
    total_charging_cycle_capacity:
      name: "${name} total charging cycle capacity"
    balancing_current:
      name: "${name} balancing current"
    errors_bitmask:
      name: "${name} errors bitmask"

switch:
  - platform: bms_to_inverter
    test_switch:
      name: "${name} Test Switch"

  - platform: ble_client
    ble_client_id: client0
    id: ble_client_switch0
    name: "${name} enable bluetooth connection"

text_sensor:
  - platform: bms_to_inverter
    charge_status:
      name: "${name} Inverter Charge Status"

  - platform: jk_bms_ble
    errors:
      name: "${name} errors"
    total_runtime_formatted:
      name: "${name} total runtime formatted"
